### ISSUE TITLE
Oil nodes missing on map

### ISSUE THREAD

**Issue by Stanzilla** [AnthorNet/SC-InteractiveMap#269]
# Issue
When important a savegame to check out Oil spawns, I noticed quite a few are missing, especially the pure ones on the left side on the map at the coast

## Replication
1. Load savegame
2. Check map for oil spawns

### Actual Result
Missing oil spawns on map

### Expected Result
All oil spawns on map 
[Ostmark mit Abso.zip](https://github.com/AnthorNet/SC-InteractiveMap/files/9873730/Ostmark.mit.Abso.zip)

**Comment by AnthorNet** [comment]
Under map options, you can show nodes icons on miner.
![image](https://user-images.githubusercontent.com/654353/198225477-fc765def-3814-4050-9159-24dacb6998a1.png)

**Comment by nsymms** [comment]
These oil wells don't show up on the interactive map for me either.  All the other oil wells show up fine (haven't verified them all).  I've tried Firefox, Chrome, and Edge.

I'm on Update 7 Early Access.  I first noticed this with Update 5, about the same time as the OP.

**Edit:** Okay, it's the classic "Resource Node" vs "Resource Well" selection.

Since crude oil is a liquid, I assumed I had to select **Resource Wells**, and that's not it.  **They're nodes**.  The wells are the ones that require the Resource Well Pressurizer and Extractor.
