### ISSUE TITLE
ficsit-networks: unimplemented ... FINLuaEventRegistry

### ISSUE THREAD

**Issue by lokzz** [AnthorNet/SC-InteractiveMap#390]
# Issue
title

## Replication
1. use a save file w/ficsit-networks & load it 

### Actual Result
ui returns "undefined"
console returns
```
Uncaught Error: Unimplemented `/Script/FicsItNetworksLua.FINLuaEventRegistry` in readFINLuaProcessorStateStorage
    at ya.readFINLuaProcessorStateStorage (Read.js?v=1730198931:1:89445)
```

### Expected Result
to load/skip ficsit-network buildings

**Comment by lattaai5** [comment]
Hello, I tried to fix the issue

This is what I did:

Added a case to handle '/Script/FicsItNetworksLua.FINLuaEventRegistry' in the readFINLuaProcessorStateStorage function. This should allow the save file to load without throwing an error for FicsIt-Networks mod structures.

I also created pull request: https://github.com/AnthorNet/SC-InteractiveMap/pull/391


> [!CAUTION]
> Disclaimer: This fix was created by Latta AI and you should never merge before you check the correctness of generated code!
>
> The fix provided by Latta AI might not be complete and it can serve as an inspiration.

---
This bug was fixed for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt fixing issues on your repository, you can block this account.

**Comment by AnthorNet** [comment]
Please provide save for debugging, I'll fix it after my annual leave mid-November

**Comment by lokzz** [comment]
k
[Save_011024-090218 - Copy.txt](https://github.com/user-attachments/files/17686232/Save_011024-090218.-.Copy.txt)
(note github forces certain file extensions, rename to .sav sry)

**Comment by AnthorNet** [comment]
Are you sure this is the correct save, that one loads perfectly here

**Comment by jubaleth** [comment]
Heya! I'm having the same issue (same error in the console)
![image](https://github.com/user-attachments/assets/79458860-3eae-4fb2-bbdf-785ba566061e)


[FicsitNetworks-Broken-Save.txt](https://github.com/user-attachments/files/17732169/FicsitNetworks-Broken-Save.txt)

Same as above, had to change the extension to txt to upload here. 

Not sure if helpful but I'm running Chrome Version 130.0.6723.117 (Official Build) (64-bit), and have tried in an incognito tab to see if it might have been something locally cached/stored but no success.
