### ISSUE TITLE
Changing color swatch doesnt apply correct colors

### ISSUE THREAD

**Issue by FrostedNxts** [AnthorNet/SC-InteractiveMap#400]
# Issue
I tried to apply Caterium Finish to all of my building but instead it put swatch 18

## Replication
1. select some buildings
2. change color to caterium finish

### Actual Result
color swatch 18 is applied

### Expected Result
caterium finish is applied

**Comment by FrostedNxts** [comment]
i also tried this with copper and silver finishes but they either didnt apply anything or they applied Factory Default swatch.

**Comment by AnthorNet** [comment]
I could not reproduce it
![image](https://github.com/user-attachments/assets/5cf15cf6-dc23-4116-b332-691de3196b6c)

Can I get the faulty save or a new one specific to test?

**Comment by thibeastmo** [comment]
I have had the same bug. Try it with these save files:
https://drive.google.com/drive/folders/1FLyfBnbHkEpw5UJhWeNue5BALljxwhCu?usp=drive_link

Solo_autosave_1_CALCULATOR = save file where you have to apply the caterium finish to buildings (I managed to set the chrome finish to all walls, therefor the _CALCULATOR in the name)
Solo_autosave_1_CALCULATOR_CALCULATOR = save file where the caterium finish should have been applied to all buildings but it shows the swatch instead. Those with the caterium finish already had it applied manually in game.

**Comment by thibeastmo** [comment]
![image_2024-12-08_185840467](https://github.com/user-attachments/assets/5ecf6646-34f3-47c0-aa76-c6e5df004bae)

When you select the caterium finish, it will set Swatch 18 as the color that should be used. In my case, that's still blue/cyan. When you select copper, it will actually set the finish to copper. But when you download the save file from the interactive map after you have set the finish to coppper, it won't use the copper finish on the building but the FICSIT Factory Swatch instead.
So:
chrome finish -> Swatch 17 (in interactive map already)
copper finish -> FICSIT Factory Swatch (only in game, because in the interactive map it will actually say copper finish)
caterium finish -> Swatch 18 (in interactive map already)
carbon steel finish -> Swatch 17 (in interactive map already)
