### ISSUE TITLE
Feature Request: Ability to place power poles at ground level with click

### ISSUE THREAD

**Issue by Schlenkat** [AnthorNet/SC-InteractiveMap#65]
I really like the roads overlay, and I want to make it my power line backbone. Ideally, I'd be able to select a power pole placer, then click on the map to plop them in (at ground level). They would mostly be for marking the road in-game, then I'd go through and tidy them up. I'm a big fan of the application!

So far I've tried using Fill With but no option for power poles and I've looked for blueprints but to no avail. My next step is going to be filling the area above roads with foundations and adding in the power poles and deleting the foundations but it'll be sloppy hehe

**Comment by ShinoHarvest** [comment]
in my opinion this is very problematic it will be necessary to integrate a very large 3d map for this function because the ground level is relative between the grotes and the cliffs there can be several ground level for an x & y.
this is only my opinion but this function may add a lot of weight to the editor to be feasible.

**Comment by AnthorNet** [comment]
Ground will not be possible, but we can expand the spawn feature to spawn a variety of game building

**Comment by Schlenkat** [comment]
How about instead a tower of foundations to act as a marker? I can run around in-game and delete a chunk of it and use that spot, then delete the rest in the save editor. Then, it'd just be as simple as letting me spawn the tower around a foundation
